using iTextSharp.text;
using iTextSharp.text.pdf;

namespace HR_PayRoll_Management.Helpers
{
    public class PdfPageEvent : PdfPageEventHelper
    {

        public override void OnEndPage(
            PdfWriter writer,
            Document document)
        {

            PdfPTable footer =
                new PdfPTable(1);


            footer.TotalWidth =
                document.PageSize.Width - 80;


            PdfPCell cell =
                new PdfPCell(
                    new Phrase(
                    "Generated by HR Payroll System"
                    ));


            cell.Border =
                Rectangle.NO_BORDER;


            cell.HorizontalAlignment =
                Element.ALIGN_CENTER;


            footer.AddCell(cell);



            footer.WriteSelectedRows(
                0,
                -1,
                40,
                30,
                writer.DirectContent);

        }

    }
}